# Generated by Django 4.2.7 on 2024-03-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_blog_comments_comments_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
