# Generated by Django 4.2.7 on 2024-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='blog_img/'),
        ),
    ]
